### ISSUE TITLE
执行远程命令时的一点小问题

### ISSUE THREAD

**Issue by Zhuazizizi** [TimeRainStarSky/TRSS-Plugin#11]
服务器win，trss-yunzai，前台运行
我在使用 rc + 任意Shell命令 后，前台的机器人窗口会突然缩小（看起来就像分辨率变低了）然后本来正常显示的中文被变成乱码，无论Shell命令执行成功或失败都会出现这个情况，有什么办法解决吗，或者有恢复窗口的方法吗。

![IMG_20240718_073311.png](https://github.com/user-attachments/assets/e0d61606-e47a-4422-858c-39b61d7aecf0)

**Comment by TimeRainStarSky** [comment]
使用 Windows 终端或 mintty 等终端模拟器
