### ISSUE TITLE
扫码登录过期失败

### ISSUE THREAD

**Issue by QAQQL** [TimeRainStarSky/TRSS-Plugin#12]
![图片](https://github.com/user-attachments/assets/4dce2a0e-c21a-4478-8a56-dc6f6b19add7)

**Comment by TimeRainStarSky** [comment]
发送
```
#更新日志TRSS-Plugin
```
截图

**Comment by QAQQL** [comment]
![图片](https://github.com/user-attachments/assets/3850d920-6d09-4ad3-92a6-75906c2f9f1f)
卡不出来

**Comment by TimeRainStarSky** [comment]
```
#强制更新TRSS-Plugin
```

**Comment by QAQQL** [comment]
不过我新搭建的
用的
```shell

#安装genshin
#安装miao-plugin
#安装TRSS-Plugin

```

**Comment by TimeRainStarSky** [comment]
扫码后米游社显示截图

**Comment by HDTianRu** [comment]
崩坏三的appid也寄了，建议用未定事件簿的appid=2

**Comment by HDTianRu** [comment]
逍遥插件也用的这个appid，还能用

**Comment by QAQQL** [comment]
重新安装后登录选项为未定事件簿,可以登录
