### ISSUE TITLE
使用脚本安装语音合成功能时报错

### ISSUE THREAD

**Issue by strike94** [TimeRainStarSky/TRSS-Plugin#7]
系统版本为Debian 11.1 ，使用trss脚本一键安装语音合成时，提示报错The currently activated Python version 3.11.3 is not supported by the project (>=3.10,<3.11).Trying to find and use a compatible version.  是需要我在容器外部重新安装3.10吗

**Comment by TimeRainStarSky** [comment]
已知问题，等修复

**Comment by TheTychoStar** [comment]
我的问题是这样的，AWS Linux。找到了Python 3.11但是后面还是报错找不到rembg命令，求教。另外开始还有个warning。

图片背景去除错误：Error: Command failed: bash '/home/ec2-user/Miao-Yunzai/plugins/TRSS-Plugin/RemBG/'main.sh i input.png output.png
Warning: Found deprecated key 'default' or 'secondary' in pyproject.toml configuration for source BFSU. Please provide the key 'priority' instead. Accepted values are: 'default', 'primary', 'secondary', 'supplemental', 'explicit'.
The currently activated Python version 3.7.16 is not supported by the project (>=3.10,<3.12).
Trying to find and use a compatible version. 
Using python3.11 (3.11.3)
Command not found: rembg

**Comment by TimeRainStarSky** [comment]
> 我的问题是这样的，AWS Linux。找到了Python 3.11但是后面还是报错找不到rembg命令，求教。另外开始还有个warning。
> 
> 图片背景去除错误：Error: Command failed: bash '/home/ec2-user/Miao-Yunzai/plugins/TRSS-Plugin/RemBG/'main.sh i input.png output.png
> Warning: Found deprecated key 'default' or 'secondary' in pyproject.toml configuration for source BFSU. Please provide the key 'priority' instead. Accepted values are: 'default', 'primary', 'secondary', 'supplemental', 'explicit'.
> The currently activated Python version 3.7.16 is not supported by the project (>=3.10,<3.12).
> Trying to find and use a compatible version. 
> Using python3.11 (3.11.3)
> Command not found: rembg

rembg 不支持 3.11，预计几个月内支持，等支持后更新
